# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
- group: IAC-Non-Prod

pool:
  name: VMSS-Windows-PROD

# Run pipeline tasks in container using FA standard build image
container:
  image: ssppaps1arpscr1.azurecr.io/wincore19-vs19ent-arps-buildimage3
  endpoint: DevOps-ACR-PROD
  
steps:
- task: AWS-Azure-Login-Config@1
  inputs:
    AzureDefaultUsername: '$(AZURE_WINDOWS_USERNAME)'
    AzureDefaultPassword: '$(AZURE_DEFAULT_PASSWORD)'
    AppName: 'AWS-ESSC-N-0'
    ProgrammaticRoleARN: '$(AZURE_DEFAULT_ROLE_ARN)'
    ProgrammaticProfileName: '$(AWS_PROG_PROFILE)'
    AssumedRoleARN: '$(AWS_ASSUMED_ROLE_ARN)'
    AssumedProfileName: 'tmct_n1_default_devops'
    ProfileRegion: 'us-west-2'
    ActivationDuration: '8'
    InstallAWSCLI: false
    InstallAWSAzureLogin: true
    DebugMode: false

- script: |
    cd "Solutions/TagCrawlerCdk"
    npm install
  displayName: 'npm install'
  
- script: |
    cd "Solutions/TagCrawlerCdk"
    npm run build
  displayName: 'build sourceCode'

- script: |
    cd "Solutions/TagCrawlerCdk"
    npm run s
    npm run d
  displayName: 'deploy'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/Solutions/TagCrawlerCdk'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: First-American-Nexus-Upload-Download@1
  inputs:
    CommandType: 'Upload'
    UploadLargeFile: true
    ServiceConnection: 'Nexus'
    SourceFilePath: '$(Build.ArtifactStagingDirectory)'
    CompressFile: true
    RepositoryName: '$(System.TeamProject)'
