trigger: none

schedules:
  - cron: "0 12 * * *"
    displayName: Every day at 7 pm
    branches:
      include:
      - master
    always: true

pool:
  name: VMSS-Windows-DEV

variables:
  - group: 'IAC-Non-Prod'

# Run pipeline tasks in container using FA standard build image
container:
  image: ssppaps1arpscr1.azurecr.io/wincore19-vs19ent-arps-buildimage3
  endpoint: DevOps-ACR-PROD

steps:
- task: AWS-Azure-Login-Config@1
  inputs:
    AzureDefaultUsername: '$(AZURE_WINDOWS_USERNAME)'
    AzureDefaultPassword: '$(AZURE_DEFAULT_PASSWORD)'
    AppName: 'AWS-ESSC-N-0'
    ProgrammaticRoleARN: '$(AZURE_DEFAULT_ROLE_ARN)'
    ProgrammaticProfileName: '$(AWS_PROG_PROFILE)'
    AssumedRoleARN: '$(AWS_ASSUMED_ROLE_ARN)'
    AssumedProfileName: 'TMCT_programmatic'
    ProfileRegion: 'us-west-2'
    ActivationDuration: '8'
    InstallAWSCLI: true
    InstallAWSAzureLogin: true
    DebugMode: false

- task: PowerShell@2
  inputs:
   targetType: inline
   workingDirectory: $(System.DefaultWorkingDirectory)
   script: | 
    echo  $(System.DefaultWorkingDirectory)
    echo "Starting..."
    $tableNames = aws dynamodb list-tables --profile TMCT_programmatic --query TableNames | ConvertFrom-Json
    $errorTables = @{"testtable1"=$True; "user"=$True; "iam_provisioned"=$True;"employee2"=$True;"employeepoc"=$True;"user-table-pr"=$True}
    $lowThreshold = $tableNames.Length
    if($lowThreshold -eq 0)
    {
        echo "No DynamoDB Tables present"
        exit 1
    }
    foreach($table in $tableNames) 
    {
        $modifiedTableName = $table.Trim();
    
        if($errorTables[$table.ToLower()])
        {
            continue
        }
        try
        {
            aws dynamodb update-table --table-name $modifiedTableName --billing-mode "PAY_PER_REQUEST" --profile TMCT_programmatic
        }
        catch [AccessDeniedException]
        {
        "The current user does not have the required role or permission to edit this DynamoDB table's settings"
        }
        catch [ResourceInException] 
        {
        "An occured attempting to change a resource which is in use"
        }
        catch 
        {
        "An error occured that could not be resolved"
        }
    }
    echo "Finished"
    exit 0

