//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Company
	{
		public virtual string Name
		{
			get;
			set;
		}

        public virtual string Name2
        {
            get;
            set;
        }


        public virtual string PhoneNumber
		{
			get;
			set;
		}

		public virtual string AccountNumber
		{
			get;
			set;
		}

		public virtual string ContactPerson
		{
			get;
			set;
		}

		public virtual string Email
		{
			get;
			set;
		}

		public virtual string GABCode
		{
			get;
			set;
		}

		public virtual string FaxNumber
		{
			get;
			set;
		}

        public virtual Address Address
        {
            get;
            set;
        }

        public virtual int? BUID
        {
            get;
            set;
        }
    }
}

