//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DocumentInfo
	{

        public virtual string FileNumber
        {
            get;
            set;
        }

        public virtual decimal SalesPrice
        {
            get;
            set;
        }

        public virtual TransactionType TransactionType
        {
            get;
            set;
        }

        public virtual string EscrowOfficerName
        {
            get;
            set;
        }

        public virtual string EscrowOfficerEmail
        {
            get;
            set;
        }

        public virtual string EscrowOfficerPhoneNumber
        {
            get;
            set;
        }

        public virtual string EscrowOfficerFaxNumber
        {
            get;
            set;
        }

        public virtual Company EscrowOffice
        {
            get;
            set;
        }

        //public virtual Company OutsideTitleCompany
        //{
        //    get;
        //    set;
        //}

        public virtual Property Property
        {
            get;
            set;
        }

        public virtual List<Buyer> BuyerCollection {
            get;
            set;
        }

        public virtual List<Borrower> BorrowerCollection
        {
            get;
            set;
        }

        public virtual List<Seller> SellerCollection
        {
            get;
            set;
        }
  //      public virtual IEnumerable<ESignDocument> ESignDocumentCollection
		//{
		//	get;
		//	set;
		//}
		
	}
}

