//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ESignDocument
	{
        public virtual string DocumentType
        {
            get;
            set;
        }

		public virtual DateTime SigningDate
		{
			get;
			set;
		}

        public virtual Signature Signature
        {
            get;
            set;
        }
        
    }
}

