//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Order
	{
		public virtual FileInfo FileInfo
		{
			get;
			set;
		}

		public virtual DocumentInfo DocumentInfo
		{
			get;
			set;
		}

	}
}

