//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public static class BuyerDocumentType
	{
		public const string AUTH_TO_RELEASE_INFO_TO_FIRST_AM_BUYER = "AUTH TO RELEASE NFO TO FIRST AM BUYER";
        public const string TERMS_AND_CONDITIONS_REO = "TERMS AND CONDITIONS REO";

    }
}
