//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public static class BuyerAndSellerDocumentType
	{
        public const string BUSINESS_DISCLOSURE_STATEMENT_HOMESMART = "BUSINESS DISCLOSURE STATEMENT HOMESMART";
		public const string BUSINESS_DISCLOSURE_STATEMENT_LEGENDARY = "BUSINESS DISCLOSURE STATEMENT LEGENDA";
        public const string BUSINESS_DISCLOSURE_STATEMENT_RL = "BUSINESS DISCLOSURE STATEMENT RL";
        public const string BUSINESS_DISCLOSURE_STATEMENT_SIGNATURE = "BUSINESS DISCLOSURE STATEMENT SIGNATURE";

        
        public const string TERMS_AND_CONDITIONS_SALE_REFI = "TERMS AND CONDITIONS SALE REFI";
    }
}
