//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public static class SellerDocumentType
    {
        public const string _1099_S = "1099-S";
        public const string SELLER_CERT_NO_INFO_REPORTING = "SELLER CERT NO INFO REPORTING";
        public const string AUTH_TO_RELEASE_INFO_TO_FIRST_Seller = "AUTH TO RELEASE INFO TO FIRST Seller";
        public const string FIRPTA = "FIRPTA";

    }
}
