//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CP.DTO.FastFileData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum TransactionType : int
    {
        

    SALE_W_MORTGAGE = 1,
    SALE_CASH = 2,
    REFINANCE = 3,
    EQUITY_LOAN = 4,
    BULK_SALE = 5,
    SEARCH_PACKAGE = 7,
    LIMITED_ESCROW = 9,
    SALE_EXCHANGE = 10,
    REO = 836,
    FORECLOSURE = 251,
    ACCOMMODATION = 837,
    SETTLEMENT_STATEMENT_ONLY = 1244,
    CONSTRUCTION_DISBURSEMENT = 1245,
    SECOND_MORTGAGE = 1246,
    REO_SALE_W_MORTGAGE = 1656,
    REO_SALE_CASH = 1657,
    SHORT_SALE_W_MORTGAGE = 1842,
    SHORT_SALE_CASH = 1843,
    SALE_W_CONSTRUCTION_LOAN = 2994,
    MTG_MOD_W_ENDORSEMENT = 2995,
    MTG_MOD_W_INCREASED_LIABILITY = 2996,
    CONSTRUCTION_FINANCE = 2997,



     //   //Sale w/Mortgage
     //   SALE = 1,

     //   //Sale/Cash
     //   CASH = 2,

     //   //Refinance
     //   REFI = 3,

     //   //EquityLoan
     //   LOAN = 4,

	    //UNKNOWN = 5,

     //   //Sale/Exchange
     //   EXCHANGE = 10,

     //   //REO
     //   REO = 836,
        
     //   //Short Sale
     //   SHTSALE = 1646,

     //   //REO Sale w/Mortgage
     //   REOMORTG = 1656,

     //   //REO Sale/Cash
     //   REOCASH = 1657,

     //   //Short Sale w/Mortgage
     //   SHTSALEMG = 1842,
        
     //   //Short Sale/Cash
     //   SHTSALECH = 1843,

     //   //Sale w/Construction Loan
     //   SALECONSLN = 2994,
        
    }
}
